const productImage = (id, view = "main") =>
  `/images/products/${id}${view === "extra" ? "-extra" : ""}.svg`;
export const products = [
  {
    id: "casque",
    name: "Casque sans fil Studio",
    category: "High-tech",
    price: 24900,
    oldPrice: 32000,
    image: productImage("casque"),
    extra: productImage("casque", "extra"),
    rating: 4.8,
    reviews: 24,
    badge: "BEST-SELLER",
    color: "Sable",
    stock: 18,
    description:
      "Votre bulle de douceur, partout. Un casque au design épuré, avec des coussinets confortables et un son équilibré pour accompagner vos journées.",
    specs: [
      "Connexion Bluetooth 5.3",
      "Autonomie jusqu’à 30 heures",
      "Microphone intégré · Recharge USB-C",
    ],
    review:
      "Très agréable à porter, et le son est vraiment bon. Mon nouveau compagnon au quotidien.",
  },
  {
    id: "sac",
    name: "Sac porté épaule Élise",
    category: "Mode",
    price: 18500,
    oldPrice: null,
    image: productImage("sac"),
    extra: productImage("sac", "extra"),
    rating: 4.9,
    reviews: 18,
    badge: "COUP DE CŒUR",
    color: "Cognac",
    stock: 12,
    description:
      "Une silhouette intemporelle et juste ce qu’il faut d’espace. Le sac Élise accueille vos essentiels avec élégance, du bureau aux sorties du week-end.",
    specs: [
      "Similicuir texturé de qualité",
      "Doublure et poche intérieure",
      "Dimensions : 28 × 21 × 10 cm",
    ],
    review:
      "La couleur est magnifique et la taille parfaite pour mes affaires. Très satisfaite !",
  },
  {
    id: "baskets",
    name: "Baskets Essential",
    category: "Mode",
    price: 22000,
    oldPrice: 28000,
    image: productImage("baskets"),
    extra: productImage("baskets", "extra"),
    rating: 4.7,
    reviews: 32,
    badge: "−21 %",
    color: "Blanc / caramel",
    stock: 20,
    description:
      "Une paire facile à aimer et à porter. Des lignes sobres, une semelle confortable et un style qui s’associe à toutes vos envies.",
    specs: [
      "Pointures disponibles : 38 à 43",
      "Semelle en caoutchouc",
      "Tige synthétique · Coupe standard",
    ],
    review: "Confortables dès le premier jour. Elles vont avec tout !",
  },
  {
    id: "serum",
    name: "Sérum éclat botanique",
    category: "Beauté",
    price: 9500,
    oldPrice: null,
    image: productImage("serum"),
    extra: productImage("serum", "extra"),
    rating: 4.8,
    reviews: 16,
    badge: "NOUVEAU",
    color: "30 ml",
    stock: 25,
    description:
      "Un geste simple pour une routine qui fait du bien. Une texture légère et une formule hydratante pour retrouver une peau douce et lumineuse.",
    specs: [
      "Flacon de 30 ml avec pipette",
      "Usage quotidien · Tous types de peaux",
      "Tester sur une petite zone avant usage",
    ],
    review:
      "Texture légère et agréable. Le flacon est aussi très joli dans ma salle de bain.",
  },
  {
    id: "lampe",
    name: "Lampe de table Alma",
    category: "Maison",
    price: 16500,
    oldPrice: 20000,
    image: productImage("lampe"),
    extra: productImage("lampe", "extra"),
    rating: 4.6,
    reviews: 12,
    badge: "",
    color: "Naturel",
    stock: 8,
    description:
      "La lumière qu’il manquait à votre intérieur. Une lampe aux lignes douces pour créer une atmosphère chaleureuse sur une table de chevet ou un bureau.",
    specs: [
      "Hauteur : 35 cm",
      "Douille E27 · Ampoule non incluse",
      "Alimentation secteur 220 V",
    ],
    review: "Une lumière très douce et un beau rendu dans mon salon.",
  },
  {
    id: "montre",
    name: "Montre connectée Active",
    category: "High-tech",
    price: 29900,
    oldPrice: 39000,
    image: productImage("montre"),
    extra: productImage("montre", "extra"),
    rating: 4.7,
    reviews: 21,
    badge: "−23 %",
    color: "Argent",
    stock: 15,
    description:
      "Gardez le rythme sans perdre le style. Notifications, suivi d’activité et cadran élégant : les essentiels réunis à votre poignet.",
    specs: [
      "Compatible Android et iOS",
      "Suivi des pas et des activités",
      "Bracelet réglable · Câble inclus",
    ],
    review:
      "Facile à utiliser et très pratique pour suivre mes pas au quotidien.",
  },
  {
    id: "vase",
    name: "Vase céramique Terra",
    category: "Maison",
    price: 8500,
    oldPrice: null,
    image: productImage("vase"),
    extra: productImage("vase", "extra"),
    rating: 4.9,
    reviews: 9,
    badge: "",
    color: "Terracotta",
    stock: 11,
    description:
      "Un bel objet, tout simplement. Sa finition mate et sa silhouette sculpturale donnent du caractère à votre intérieur, avec ou sans bouquet.",
    specs: [
      "Céramique · Finition mate",
      "Hauteur : 22 cm",
      "Nettoyage avec un chiffon doux",
    ],
    review:
      "Encore plus beau en vrai. Il apporte une jolie touche à mon intérieur.",
  },
  {
    id: "lunettes",
    name: "Lunettes de soleil Riviera",
    category: "Mode",
    price: 7500,
    oldPrice: 10000,
    image: productImage("lunettes"),
    extra: productImage("lunettes", "extra"),
    rating: 4.6,
    reviews: 14,
    badge: "−25 %",
    color: "Écaille",
    stock: 24,
    description:
      "Des journées ensoleillées, un style affirmé. Une monture légère et intemporelle à emporter partout avec vous.",
    specs: [
      "Protection UV400",
      "Monture légère en acétate",
      "Étui souple inclus",
    ],
    review:
      "Très belles lunettes, légères et confortables. Excellent rapport qualité-prix.",
  },
];
export const shippingFee = (subtotal) => (subtotal >= 50000 ? 0 : 1500);
